name: CI

on:
  push:
    paths-ignore: ['**.md', '**.adoc']
  pull_request:
    paths-ignore: ['**.md', '**.adoc']

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        emacs_version: ['27.1', '28.1']

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Download cache by .eldev
      uses: actions/download-artifact@v3

    - name: Compile the project
      run: eldev compile --set all --warnings-as-errors

    - name: Test the project
      run: eldev test

    - name: Archive .eldev artifacts
      uses: actions/upload-artifact@v3
      with:
          name: eldev-cache
